create table if not exists public.scheduled_scan_attempts (
  id uuid primary key default gen_random_uuid(),
  attempt_fingerprint text not null unique,
  trading_date date null,
  source text not null default 'unknown',
  mode text not null default 'scheduled',
  outcome text not null default 'route_received',
  allowed boolean null,
  route_received_at timestamptz null,
  scheduled_function_fired_at timestamptz null,
  utc_timestamp timestamptz not null default now(),
  ny_timestamp text null,
  official_window text not null default 'unknown',
  intraday_scan_window text null,
  orchestration_decision text null,
  skip_reason text null,
  message text null,
  http_status integer null,
  raw_count integer null,
  ranked_count integer null,
  selected_count integer null,
  built_count integer null,
  published_count integer null,
  recommendations_created integer null,
  batch_fingerprint text null,
  scan_run_fingerprint text null,
  scheduled_scan_run_id text null,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scheduled_scan_attempts_trading_date_idx
  on public.scheduled_scan_attempts (trading_date desc);

create index if not exists scheduled_scan_attempts_utc_timestamp_idx
  on public.scheduled_scan_attempts (utc_timestamp desc);

create index if not exists scheduled_scan_attempts_window_outcome_idx
  on public.scheduled_scan_attempts (official_window, outcome);

comment on table public.scheduled_scan_attempts is
  'Append/update log for Netlify scheduled scan firings and automation route outcomes. This is separate from legacy scheduled_scan_runs so same-window skips and duplicate-session attempts remain observable.';

comment on column public.scheduled_scan_attempts.attempt_fingerprint is
  'Correlation key generated by the scheduled function or route and sent through the /api/automation/run-scan request body.';
